default: &default
  sessions:
    default:
      database: openshift_broker
      hosts:
        -  localhost:27017
      username: openshift
      password: mooo
  options:
    raise_not_found_error: true
production: *default
development: *default
test: *default
